### ISSUE TITLE
Expose port of mysql service

### ISSUE THREAD

**Issue by Philoreiser** [880831ian/docker-compose-php-mysql-nginx#2]
https://github.com/880831ian/docker-compose-php-mysql-nginx/blob/master/docker-compose/Docker-compose.yml#L20-L29

透過 mysql-client 登入 MySQL console 會發生錯誤:
```
$ mysql -h 127.0.0.1 -u myuser -P 3306 -p mydb
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
```

docker-composer.yml 當中 mysql service 段落需加上 ports mapping (EXPOSE)

```
mysql:
    image: mysql:8.0.28
    container_name: mysql
    volumes:
      - ./docker-volume/mysql/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
```
